### PR TITLE
Removed singleton

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/gfx_debug_draw/issues/51
- Bumped to 0.6.0

### CODE REVIEW

**Comment by bvssvni** [comment]
@stjahns @Kagami @kvark What do you think?

**Comment by kvark** [comment]
Sounds good. How would the examples look in this case?

**Comment by stjahns** [comment]
This makes it quite a bit less convenient to use for actual debugging - if
you wanted to temporarily draw out some points/lines/etc from some
arbitrarily deep function, you'd need to refactor to pass mutable
references to the debug renderer wherever you'd need it - the singleton
wasn't intended for 'real' code, just convenience. I'd recommend just not
including it in release builds.

**Comment by bvssvni** [comment]
@stjahns Would it not be better to use something like [current](https://github.com/pistondevelopers/current)?

**Comment by bvssvni** [comment]
Fails on stable in Travis CI, but this should probably work with Gfx 0.8.

I'll merge this since the current library can be used instead of the singleton.

**Pull request merged**
